@extends('layouts.template')

@section('content')
  
  
  <div class="container-xl">
    <div class="mt-3">
        <div class="page-header mb-0">
          <div class="row align-items-center">
            <div class="col">
              {{-- <div class="mb-1">
                <ol class="breadcrumb breadcrumb-alternate" aria-label="breadcrumbs">
                  <li class="breadcrumb-item"><a href="#">Home</a></li>
                  <li class="breadcrumb-item"><a href="#">Library</a></li>
                  <li class="breadcrumb-item active" aria-current="page"><a href="#">Articles</a></li>
                </ol>
              </div> --}}
              <h2 class="page-title">
                <span class="text-truncate">My Classrooms</span>
              </h2>
            </div>
            <div class="col-auto"> 
                <a href="#" class="btn btn-azure" data-bs-toggle="modal" data-bs-target="#modalCreateClass" id="addclasslink">
                  <svg xmlns="http://www.w3.org/2000/svg" class="icon m-0" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z"></path><line x1="12" y1="5" x2="12" y2="19"></line><line x1="5" y1="12" x2="19" y2="12"></line></svg>
                  <span class="ms-2 d-none d-sm-inline-block">New Room</span>
                </a>  
            </div>
          </div>
        </div>
      </div>
  </div>
  <div class="content">
    <div class="container-xl"> 
      <div class="row">
        @foreach($myclass as $cl)
        <div class="col-md-6 mb-3">             
          <div class="card">
            <div class="card-status-bottom bg-{{$cl->colourvariant}}"></div>
            <div class="card-body">
              <div class="row row-sm align-items-center">
                <div class="col-auto avatar-list">
                  <span style="background-image: url('{{asset($cl->avatar)}}');" class="avatar avatar-lg"></span>
                </div>
                <div class="col">
                  <h4 class="card-title m-0">
                    <a href="{{route('classroom.show', $cl->classcode )}}">{{ $cl->classname }}</a>
                  </h4>
                  <div class="text-muted">{{$cl->description}}</div>
                  <div class="small mt-1">
                  <span class="text-success">●</span> {{$cl->status}}</div>
                </div>
                <div class="col-auto"> 
                  <a href="{{route('classroom.show', $cl->classcode )}}" class="btn btn-pill btn-{{$cl->colourvariant}} d-none d-md-inline-block">
                    <span><svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M10 14a3.5 3.5 0 0 0 5 0l4 -4a3.5 3.5 0 0 0 -5 -5l-.5 .5" /><path d="M14 10a3.5 3.5 0 0 0 -5 0l-4 4a3.5 3.5 0 0 0 5 5l.5 -.5" /></svg></span>Enter Class
                  </a>
                </div> 
              </div>
            </div>
          </div>
        </div>
        @endforeach
      </div>
    </div>
  </div>
  <div class="modal fade" id="modalCreateClass" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Create a new class</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form method="POST" action="{{route('classroom.store')}}">
          @csrf
          @method('POST')
          
          <div class="modal-body">
            <input type="number" name="teacher_id" value="{{ Auth::id() }}" class="form-control mb-3" hidden="">
            <div class="row mb-3 align-items-end">
              <div class="col-md-7">  
                <label class="form-label">Class Name (Alias)</label>
                <input type="text" class="form-control" id="classname" name="classname" /> 
              </div>
              <div class="col-md-5">  
                <label class="form-label">Class Code</label>
                @php
                  $generatedcode = DB::select("SELECT LEFT(MD5(NOW()), 6) as 'randomCode' FROM classrooms WHERE 'randomCode' NOT IN (SELECT `classcode` FROM `classrooms`) LIMIT 1");
                   foreach ($generatedcode as $gen) {
                     $code = $gen->randomCode;
                   }
                @endphp
                <input type="text" class="form-control text-uppercase" value="{{ $code }}" data-bs-toggle="tooltip" data-bs-html="true" data-bs-placement="bottom" title="This code is auto generated by the system" id="classcode" name="classcode" readonly="" /> 
              </div>
            </div>
            <div class="row mb-3">
              <div class="col-md-6">
                <div class="form-label">Select Course</div>
                <select name="course" class="tailSelect"> 
                  @php
                    $courses = DB::table('courses')->get();

                    foreach ($courses as $course) {
                       echo '<option value="'.$course->id.'" data-description="'.$course->description.'">'.$course->course_name.'</option>';
                    }

                  @endphp
                </select>
              </div>
              <div class="col-md-6">
                <div class="form-label">Select Grade Level</div>
                <select name="level" class="tailSelect">
                @php
                    $levels = DB::table('gradelevels')->get();

                    foreach ($levels as $level) {
                       echo '<option value="'.$level->id.'" data-description="'.$level->description.'">'.$level->level.'</option>';
                    }

                  @endphp 
                </select>
              </div>
            </div>
            <div class="mb-3">  
              <label class="form-label">Class Section</label>
              <input type="text" class="form-control" id="section" name="section" /> 
            </div>
            <div class="mb-3">
              <div class="form-label">Select Subject</div>
              <select name="subject" class="tailSelect">
                @php
                  
                  $subjects = DB::table('subjects')->get();

                  foreach ($subjects as $subject) {
                    echo '<option value="'.$subject->id.'" data-description="'.$subject->description.'">'.$subject->subject_title.'</option>';
                  }
                  
                @endphp
              </select>
            </div>
            <div class="mb-3">
              <label class="form-label">Pick your team color</label>
              <div class="row row-sm">
                <div class="col-auto">
                  <label class="form-colorinput">
                    <input name="color" type="radio" value="dark" class="form-colorinput-input" />
                    <span class="form-colorinput-color bg-dark"></span>
                  </label>
                </div>
                <div class="col-auto">
                  <label class="form-colorinput form-colorinput-light">
                    <input name="color" type="radio" value="white" class="form-colorinput-input"  checked/>
                    <span class="form-colorinput-color bg-white"></span>
                  </label>
                </div>
                <div class="col-auto">
                  <label class="form-colorinput">
                    <input name="color" type="radio" value="blue" class="form-colorinput-input" />
                    <span class="form-colorinput-color bg-blue"></span>
                  </label>
                </div>
                <div class="col-auto">
                  <label class="form-colorinput">
                    <input name="color" type="radio" value="azure" class="form-colorinput-input" />
                    <span class="form-colorinput-color bg-azure"></span>
                  </label>
                </div>
                <div class="col-auto">
                  <label class="form-colorinput">
                    <input name="color" type="radio" value="indigo" class="form-colorinput-input" />
                    <span class="form-colorinput-color bg-indigo"></span>
                  </label>
                </div>
                <div class="col-auto">
                  <label class="form-colorinput">
                    <input name="color" type="radio" value="purple" class="form-colorinput-input" />
                    <span class="form-colorinput-color bg-purple"></span>
                  </label>
                </div>
                <div class="col-auto">
                  <label class="form-colorinput">
                    <input name="color" type="radio" value="pink" class="form-colorinput-input" />
                    <span class="form-colorinput-color bg-pink"></span>
                  </label>
                </div>
                <div class="col-auto">
                  <label class="form-colorinput">
                    <input name="color" type="radio" value="red" class="form-colorinput-input" />
                    <span class="form-colorinput-color bg-red"></span>
                  </label>
                </div>
                <div class="col-auto">
                  <label class="form-colorinput">
                    <input name="color" type="radio" value="orange" class="form-colorinput-input" />
                    <span class="form-colorinput-color bg-orange"></span>
                  </label>
                </div>
                <div class="col-auto">
                  <label class="form-colorinput">
                    <input name="color" type="radio" value="yellow" class="form-colorinput-input" />
                    <span class="form-colorinput-color bg-yellow"></span>
                  </label>
                </div>
                <div class="col-auto">
                  <label class="form-colorinput">
                    <input name="color" type="radio" value="lime" class="form-colorinput-input" />
                    <span class="form-colorinput-color bg-lime"></span>
                  </label>
                </div>
              </div>
            </div>
            <div class="mb-3">
              <label class="form-label">Choose your avatar</label>
              <div class="row row-sm">
                <div class="col-auto px-1">
                  <label class="form-imagecheck mb-2">
                    <input type="radio" name="avatar" value="./static/doodle/doodle-01.svg" class="form-imagecheck-input" checked/>
                    <span class="form-imagecheck-figure">
                      <img src="./static/doodle/doodle-01.svg" class="form-imagecheck-image avatar avatar-md">
                    </span>
                  </label>
                </div>
                <div class="col-auto px-1">
                  <label class="form-imagecheck mb-2">
                    <input type="radio" name="avatar" value="./static/doodle/doodle-72.svg" class="form-imagecheck-input"/>
                    <span class="form-imagecheck-figure">
                      <img src="./static/doodle/doodle-72.svg" class="form-imagecheck-image avatar avatar-md">
                    </span>
                  </label>
                </div>
                <div class="col-auto px-1">
                  <label class="form-imagecheck mb-2">
                    <input type="radio" name="avatar" value="./static/doodle/doodle-65.svg" class="form-imagecheck-input"/>
                    <span class="form-imagecheck-figure">
                      <img src="./static/doodle/doodle-65.svg" class="form-imagecheck-image avatar avatar-md">
                    </span>
                  </label>
                </div>
                <div class="col-auto px-1">
                  <label class="form-imagecheck mb-2">
                    <input type="radio" name="avatar" value="./static/doodle/doodle-39.svg" class="form-imagecheck-input"/>
                    <span class="form-imagecheck-figure">
                      <img src="./static/doodle/doodle-39.svg" class="form-imagecheck-image avatar avatar-md">
                    </span>
                  </label>
                </div>
                <div class="col-auto px-1">
                  <label class="form-imagecheck mb-2">
                    <input type="radio" name="avatar" value="./static/doodle/doodle-17.svg" class="form-imagecheck-input"/>
                    <span class="form-imagecheck-figure">
                      <img src="./static/doodle/doodle-17.svg" class="form-imagecheck-image avatar avatar-md">
                    </span>
                  </label>
                </div>
                <div class="col-auto px-1">
                  <label class="form-imagecheck mb-2">
                    <input type="radio" name="avatar" value="./static/doodle/doodle-75.svg" class="form-imagecheck-input"/>
                    <span class="form-imagecheck-figure">
                      <img src="./static/doodle/doodle-75.svg" class="form-imagecheck-image avatar avatar-md">
                    </span>
                  </label>
                </div>
                <div class="col-auto px-1">
                  <label class="form-imagecheck mb-2">
                    <input type="radio" name="avatar" value="./static/doodle/doodle-81.svg" class="form-imagecheck-input"/>
                    <span class="form-imagecheck-figure">
                      <img src="./static/doodle/doodle-81.svg" class="form-imagecheck-image avatar avatar-md">
                    </span>
                  </label>
                </div>
                <div class="col-auto px-1">
                  <label class="form-imagecheck mb-2">
                    <input type="radio" name="avatar" value="./static/doodle/doodle-97.svg" class="form-imagecheck-input"/>
                    <span class="form-imagecheck-figure">
                      <img src="./static/doodle/doodle-97.svg" class="form-imagecheck-image avatar avatar-md">
                    </span>
                  </label>
                </div>
                <div class="col-auto px-1">
                  <label class="form-imagecheck mb-2">
                    <input type="radio" name="avatar" value="./static/doodle/doodle-70.svg" class="form-imagecheck-input"/>
                    <span class="form-imagecheck-figure">
                      <img src="./static/doodle/doodle-70.svg" class="form-imagecheck-image avatar avatar-md">
                    </span>
                  </label>
                </div>
                <div class="col-auto px-1">
                  <label class="form-imagecheck mb-2">
                    <input type="radio" name="avatar" value="./static/doodle/doodle-73.svg" class="form-imagecheck-input"/>
                    <span class="form-imagecheck-figure">
                      <img src="./static/doodle/doodle-73.svg" class="form-imagecheck-image avatar avatar-md">
                    </span>
                  </label>
                </div>
                <div class="col-auto px-1">
                  <label class="form-imagecheck mb-2">
                    <input type="radio" name="avatar" value="./static/doodle/doodle-60.svg" class="form-imagecheck-input"/>
                    <span class="form-imagecheck-figure">
                      <img src="./static/doodle/doodle-60.svg" class="form-imagecheck-image avatar avatar-md">
                    </span>
                  </label>
                </div>
                <div class="col-auto px-1">
                  <label class="form-imagecheck mb-2">
                    <input type="radio" name="avatar" value="./static/doodle/doodle-42.svg" class="form-imagecheck-input"/>
                    <span class="form-imagecheck-figure">
                      <img src="./static/doodle/doodle-42.svg" class="form-imagecheck-image avatar avatar-md">
                    </span>
                  </label>
                </div>
              </div>
            </div>
            <div>
              <label class="form-label">Description</label>
              <textarea class="form-control" name="description"></textarea>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary mr-auto" data-bs-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary" name="submit">Add Class</button> 
          </div>
        </form>
      </div>
    </div>
  </div>
@endsection

